name: Generate ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate ISO via Docker
        run: |
          mkdir output
          docker run --privileged --rm \
            -v ./output:/build-out \
            -e FEDORA_MAJOR_VERSION=41 \
            ghcr.io/ublue-os/isogenerator:latest \
            IMAGE_URL=ghcr.io/alexspina/ambra-os \
            IMAGE_TAG=latest \
            VARIANT=silverblue \
            ISO_NAME=Ambra-OS.iso

      - name: Upload ISO as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ambra-OS-ISO
          path: output/Ambra-OS.iso
