name: KeyGen
on: workflow_dispatch
jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@v3.3.0
      - run: |
          # Generiamo le chiavi senza password (fondamentale!)
          cosign generate-key-pair
          echo "--- COPIA DA QUI SOTTO (PRIVATE) ---"
          cat cosign.key
          echo "--- COPIA DA QUI SOTTO (PUBLIC) ---"
          cat cosign.pub
